theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "custom"
command = "echo 'T'"
on_click = 'swaymsg exec alacritty'
interval = "once"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}%"
format_swap = "{swap_used_percents}%"

[[block]]
block = "cpu"
interval = 4

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "battery"
allow_missing = true
hide_missing = true

[[block]]
block = "sound"
